# Generated by Django 5.2 on 2025-04-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_size',
            field=models.PositiveIntegerField(default='0', editable=False, max_length=100),
        ),
    ]
