# Generated by Django 5.2 on 2025-04-23 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_size',
            field=models.PositiveIntegerField(default='0', editable=False, validators=[django.core.validators.MaxValueValidator(1048576)]),
        ),
    ]
