# Generated by Django 5.2 on 2025-04-19 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_colleges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='university.college'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_college_name', violation_error_message='College name must be unique'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_college_code', violation_error_message='College code must be unique'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_department_name', violation_error_message='Department name must be unique '),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_department_code', violation_error_message='Department code must be unique '),
        ),
    ]
